const ROUTE_CHANGED = 'ROUTE_CHANGED';
const NAME_UPDATED = 'NAME_UPDATED';
const EMAIL_UPDATED = 'EMAIL_UPDATED';
const ADDRESS_UPDATED = 'ADDRESS_UPDATED';
const SSN_UPDATED = 'SSN_UPDATED';
const SSN_APPLICATION_CLICKED = 'SSN_APPLICATION_CLICKED';

module.exports = {
  ROUTE_CHANGED,
  NAME_UPDATED,
  EMAIL_UPDATED,
  ADDRESS_UPDATED,
  SSN_UPDATED,
  SSN_APPLICATION_CLICKED,
};
